### ISSUE TITLE
Conv2D Error - First Layer of CNN

### ISSUE THREAD

**Issue by Shraddha2702** [anujshah1003/own_data_cnn_implementation_keras#9]
**ValueError**: Error when checking input: expected conv2d_59_input to have 4 dimensions, 
but got an array with shape (88, 128, 128)
Things look fine to me, not sure what's wrong. 

![screenshot 5](https://user-images.githubusercontent.com/20888124/45054344-81180d00-b041-11e8-8fb5-81b295886291.png)

**Comment by JaimePv** [comment]
I'm having the same issue, but with conv2d_1_input.
ValueError: Error when checking input: expected conv2d_1_input to have 4dimensions, but got array with shape (2369, 200, 200).
Any ideas to solve it??

**Comment by JaimePv** [comment]
Finally, i solved it by moving the lines 65-68 (from the file "updated_custom_data_cnn.py") to the line 138 above the input_shape definition.

`# Defining the model`
`#Shuffle the dataset`
`x,y = shuffle(img_data,Y, random_state=2)`
`# Split the dataset`
`X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)`

`input_shape=img_data[0].shape`

`model = Sequential()`

I hope you enjoy it!
